project_name: sqs_clipboard

before:
  hooks:
    - go generate ./...
    - go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo

builds:
  - main: .
    id: "sqscopy"
    binary: sqscopy
    dir: ./cmd/sqscopy
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 7
  
  - main: .
    id: "sqscopygui"
    binary: sqscopy
    dir: ./cmd/sqscopy
    ldflags:
      - -s -w -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

  - main: .
    id: "sqspaste"
    binary: sqspaste
    dir: ./cmd/sqspaste
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 7

  - main: .
    id: "sqspastegui"
    binary: sqspaste
    dir: ./cmd/sqspaste
    ldflags:
      - -s -w -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

  - main: .
    id: "sqscopsmallfile"
    binary: sqscopysmallfile
    dir: ./cmd/sqscopysmallfile
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 7

  - main: .
    id: "sqscopysmallfilegui"
    binary: sqscopysmallfile
    dir: ./cmd/sqscopysmallfile
    ldflags:
      - -s -w -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

  - main: .
    id: "sqspastesmallfile"
    binary: sqspastesmallfile
    dir: ./cmd/sqspastesmallfile
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 7

  - main: .
    id: "sqspastesmallfilegui"
    binary: sqspastesmallfile
    dir: ./cmd/sqspastesmallfile
    ldflags:
      - -s -w -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

  - main: .
    id: "sqspurge"
    binary: sqspurge
    dir: ./cmd/sqspurge
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm
    goarm:
      - 7

  - main: .
    id: "sqspurgegui"
    binary: sqspurge
    dir: ./cmd/sqspurge
    ldflags:
      - -s -w -H windowsgui
    goos:
      - windows
    goarch:
      - amd64

archives:
   - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ .Arm }}"
     format: tar.xz
     format_overrides:
       - goos: windows
         format: zip
     replacements:
         darwin: macOS
     wrap_in_directory: true

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}--sha256_checksums.txt"

release:
  draft: true
