
TOPTARGETS := all clean

SUBDIRS := sqscopy sqspaste sqspurge sqscopysmallfile sqspastesmallfile

$(TOPTARGETS): $(SUBDIRS)
$(SUBDIRS):
	$(MAKE) -f Makefile.win -C $@ $(MAKECMDGOALS)

.PHONY: $(TOPTARGETS) $(SUBDIRS)
